spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false